# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-548d9ea6-bd25-4c2c-a0f9-449cbee8bb06";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-548d9ea6-bd25-4c2c-a0f9-449cbee8bb06".device = "/dev/disk/by-uuid/548d9ea6-bd25-4c2c-a0f9-449cbee8bb06";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6405-1A41";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-20b311c8-b910-414d-8319-5e063de4def0"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
